### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by binzcodes** [RivercodeAB/facebook-conversion-api-nextjs#16]
Running Next 11 / Node 14 on Vercel

Suspect a compatibility issue with v14 as Request isn't defined in `graph-api.js`?

```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: Request is not defined","reason":{"errorType":"ReferenceError","errorMessage":"Request is not defined","stack":["ReferenceError: Request is not defined","    at /var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/api/graph/graph-api.js:22:21","    at Generator.next (<anonymous>)","    at /var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/api/graph/graph-api.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/api/graph/graph-api.js:4:12)","    at graphApi (/var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/api/graph/graph-api.js:19:54)","    at /var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/services/server-side-events/server-side-events.js:61:32","    at Generator.next (<anonymous>)","    at /var/task/node_modules/@rivercode/facebook-conversion-api-nextjs/dist/services/server-side-events/server-side-events.js:8:71","    at new Promise (<anonymous>)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: Request is not defined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at process.emit (/var/task/___vc/__sourcemap_support.js:602:21)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by ovdahlberg** [comment]
Hi @binzcodes!

Can you try updating to version 4.3.1 and see if the issue still exist?

**Comment by binzcodes** [comment]
Thanks, I'll let you know if this resolves it.

Thanks for creating this library, a great time saver!

**Comment by binzcodes** [comment]
Sorry I didn't update but this didn't resolve for us. Build was still missing fetch.

I got it working in a fork using node-fetch but haven't had the chance to investigate further and report back.
